/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EntriesNewRouteImport } from './routes/entries/new'
import { Route as EntriesPageRouteImport } from './routes/entries/$page'
import { Route as EntriesIdEditRouteImport } from './routes/entries/$id/edit'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EntriesNewRoute = EntriesNewRouteImport.update({
  id: '/entries/new',
  path: '/entries/new',
  getParentRoute: () => rootRouteImport,
} as any)
const EntriesPageRoute = EntriesPageRouteImport.update({
  id: '/entries/$page',
  path: '/entries/$page',
  getParentRoute: () => rootRouteImport,
} as any)
const EntriesIdEditRoute = EntriesIdEditRouteImport.update({
  id: '/entries/$id/edit',
  path: '/entries/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/entries/$page': typeof EntriesPageRoute
  '/entries/new': typeof EntriesNewRoute
  '/entries/$id/edit': typeof EntriesIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/entries/$page': typeof EntriesPageRoute
  '/entries/new': typeof EntriesNewRoute
  '/entries/$id/edit': typeof EntriesIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/entries/$page': typeof EntriesPageRoute
  '/entries/new': typeof EntriesNewRoute
  '/entries/$id/edit': typeof EntriesIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/entries/$page'
    | '/entries/new'
    | '/entries/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/entries/$page' | '/entries/new' | '/entries/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/entries/$page'
    | '/entries/new'
    | '/entries/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  EntriesPageRoute: typeof EntriesPageRoute
  EntriesNewRoute: typeof EntriesNewRoute
  EntriesIdEditRoute: typeof EntriesIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entries/new': {
      id: '/entries/new'
      path: '/entries/new'
      fullPath: '/entries/new'
      preLoaderRoute: typeof EntriesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entries/$page': {
      id: '/entries/$page'
      path: '/entries/$page'
      fullPath: '/entries/$page'
      preLoaderRoute: typeof EntriesPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entries/$id/edit': {
      id: '/entries/$id/edit'
      path: '/entries/$id/edit'
      fullPath: '/entries/$id/edit'
      preLoaderRoute: typeof EntriesIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  EntriesPageRoute: EntriesPageRoute,
  EntriesNewRoute: EntriesNewRoute,
  EntriesIdEditRoute: EntriesIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
